### PR TITLE
Open redirection

### LINKED ISSUE #45: open-redirect vulnerability tester
This feature will make vault to find open-redirect vulnerability.

### PR DESCRIPTION
**Pull request by mzfr**
#### Changes this pull request makes :
Fixes #45 

All the payloads are taken from https://raw.githubusercontent.com/cujanovic/Open-Redirect-Payloads/master/Open-Redirect-payloads.txt

#### Checklist :

  - [ ] I have added the relevant documentation.
  - [x] My branch is up-to-date with the upstream master branch.
  - [x] I have fully tested the changes locally.

#### Development environment

    OS: Manjaro
    Python Version: 3.5

### CODE REVIEW

**Comment by 0xPrateek** [comment]
This issue is also also assigned to me. Please follow the steps to create PR .

**Comment by abhisharma404** [comment]
@mzfr This was assigned to 0xPrateek.
@0xPrateek What is your progress on this issue?

**Comment by 0xPrateek** [comment]
CMS detection is done just I have to CREATE  a PR . But due to 2 back to back exam of cryptography and digital design i was not getting time to work on it. Very soon I will be pushing my PR's.

**Comment by 0xPrateek** [comment]
Hope you understand the situation I am in.

**Comment by abhisharma404** [comment]
@0xPrateek Send your PR, I'll review and compare.

Hope we don't run into confusion next time :)

**Comment by 0xPrateek** [comment]
Yes very soon I will be sending the pull request.

**Comment by abhisharma404** [comment]
@mzfr Update this PR according to the current project architecture.

**Comment by abhisharma404** [comment]
@mzfr Update the Readme.

**Pull request merged**
