### PR TITLE
Admin panel finder

### LINKED ISSUE #44: Feature: Admin panel Finder for vault
This feature will help to find the admin panel of a website.

### PR DESCRIPTION
**Pull request by mzfr**
#### Changes this pull request makes :
fixes #44 
#### Checklist :

  - [ ] I have added the relevant documentation.
  - [x] My branch is up-to-date with the upstream master branch.
  - [x] I have fully tested the changes locally.

#### Development environment

    OS: Manjaro
    Python Version: 3.5

### CODE REVIEW

**Comment by abhisharma404** [comment]
@mzfr This was assigned to 0xPrateek.
@0xPrateek What is your progress on this issue?

**Comment by 0xPrateek** [comment]
Working on it  and I will write the code which works best. Not by importing modules . The code for admin panel finder in this PR is not upto mark. I don't know why to use library for everyone thing when we can do it simply. Hope I will get some time ...

**Comment by mzfr** [comment]
@abhisharma404  Again I wasn't aware of that. It would be better if we can just comment on the issue which is been already assigned to someone. I am not very active on fitter lately.
Please feel free to close the PR

**Comment by abhisharma404** [comment]
@mzfr Yes! Adding comments to issue would solve this problem next time.
@0xPrateek Can you explain me your approach in detail, modules imported in this code are still within the project default dependencies.

Well for this time, I can think we can merge this if 0xPrateek has not worked yet. I guess next time we don't have confusions :)

**Comment by abhisharma404** [comment]
@mzfr Update this PR.

**Pull request merged**
