### PR TITLE
Add logger

### LINKED ISSUE #1: logging erros
Instead of printing errors we can safely log them into a file.

### PR DESCRIPTION
**Pull request by mzfr**
Fixes #1.

This will add a new logger to vault scanner. I haven't connected the logger with any code. we can do it once you are done with the final touchups :)

### CODE REVIEW

**Comment by abhisharma404** [comment]
Looks great :) Could you add some basic documentation in the file, stating how to use the logger function, it will be a great help for the coming new developers.

**Comment by mzfr** [comment]
@abhisharma404 I have used logger to log all the errors. Please review the PR

**Comment by abhisharma404** [comment]
@mzfr I'll review it soon.

**Comment by abhisharma404** [comment]
@mzfr I don't think removing the print statement is a good idea, we can keep it.

P.S. I checked the issue, and yes the statement was not clear. Great work btw! make the changes, it's good to go. :)

**Comment by mzfr** [comment]
@abhisharma404 I have made the suggested changes

**Pull request merged**
