### PR TITLE
Fixed color for error lines

### PR DESCRIPTION
**Pull request by 0xPrateek**
This change will use colors module for displaying error lines.After commiting the changes the error lines will be displayed in red color.

#### Checklist :

  - [x] I have added the relevant documentation.
  - [x] My branch is up-to-date with the upstream master branch.
  - [x] I have fully tested the changes locally.

#### Development environment

    OS: x
    Python Version: x

### CODE REVIEW

**Comment by abhisharma404** [comment]
@0xPrateek Can you add a screenshot, it will be easier for me to see the working changes.

**Comment by 0xPrateek** [comment]
Os : parrot Linux distro
Python : 3

**Comment by 0xPrateek** [comment]
And for checking the changes in the  code you can follow this link.
https://github.com/abhisharma404/vault_scanner/pull/25/commits/3436a61c879918fa8e9fda273486a85a799a23f0

**Comment by abhisharma404** [comment]
@0xPrateek I needed the screenshot to see how the errors were being printed when ran.
Because, as far I guess, this is not enough, `error` function defined in `colors.py` does not resets the color after printing, hence everything gets printed red (color of `error` print function).

I'll work around with `colors.py` and let you know.

**Comment by 0xPrateek** [comment]
Okay.. as soon as I will be with my laptop I will forward the screenshot. Let me explain you something first..
Your colors.py module contain two function 1- success 2- error both function require an argument that is message which is to be printed. And the work of these function is just to print the message which is being passed as argument in color. So there is no possiblity of getting red color lines for success statements.
P.S within some time I will be commenting the screenshot too for more clarification ..

**Comment by abhisharma404** [comment]
@0xPrateek Try testing and playing around, you will understand what I'm trying to convey.

**Comment by 0xPrateek** [comment]
I have uploaded the screenshot in the drive . You can check it....
https://drive.google.com/open?id=1C25xRRcykJ19ImrWm06Yp4m76S9KiG_i

**Comment by 0xPrateek** [comment]
changes

**Pull request merged**
